USE BookLoversProject

CREATE TABLE Genres(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30) NOT NULL,
);

CREATE TABLE Books(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(30) NOT NULL,
Description NVARCHAR(500),
Rating FLOAT,
);

CREATE TABLE Authors(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30) NOT NULL,
Description NVARCHAR(400),
);

CREATE TABLE Readers(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(20) NOT NULL,
LastName NVARCHAR(20) NOT NULL,
ImagePath NVARCHAR(30),
Email NVARCHAR(30) NOT NULL,
Password NVARCHAR(20) NOT NULL,
);

CREATE TABLE Shelves(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30) NOT NULL,
ReaderID INT NOT NULL FOREIGN KEY REFERENCES Readers(ID),
);

CREATE TABLE Reviews(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Comment NVARCHAR(50) NOT NULL,
Date DATETIME NOT NULL,
ReaderID INT NOT NULL FOREIGN KEY REFERENCES Readers(ID),
BookID INT NOT NULL FOREIGN KEY REFERENCES Books(ID),
);

CREATE TABLE Admins(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Email NVARCHAR(30) NOT NULL,
Password NVARCHAR(20) NOT NULL,
);

CREATE TABLE BookGenres(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
BookID INT NOT NULL FOREIGN KEY REFERENCES Books(ID),
GenreID INT NOT NULL FOREIGN KEY REFERENCES Genres(ID),
);

CREATE TABLE BookAuthors(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
BookID INT NOT NULL FOREIGN KEY REFERENCES Books(ID),
AuthorID INT NOT NULL FOREIGN KEY REFERENCES Authors(ID),
);

CREATE TABLE ShelfBooks(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
BookID INT NOT NULL FOREIGN KEY REFERENCES Books(ID),
ShelfID INT NOT NULL FOREIGN KEY REFERENCES Shelves(ID),
);

CREATE TABLE ReaderAuthors(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ReaderID INT NOT NULL FOREIGN KEY REFERENCES Readers(ID),
AuthorID INT NOT NULL FOREIGN KEY REFERENCES Authors(ID),
);
